name: studybuddy
description: AI-powered NCERT Class 12 Study App
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  google_generative_ai: ^0.4.7
  flutter_markdown: ^0.7.3

  speech_to_text: ^6.6.2
  flutter_tts: ^3.8.5

  camera: ^0.10.5+9
  google_mlkit_text_recognition: ^0.11.0

  shared_preferences: ^2.3.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
